using System;
using System.Data;
using System.Configuration;
using System.Web;
using System.Web.Security;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.HtmlControls;
using System.IO;
using System.Xml;

public partial class _Default : System.Web.UI.Page 
{
    protected void Page_Load(object sender, EventArgs e)
    {
        AddressServiceClient myAddressService = new AddressServiceClient();
        string strData = myAddressService.GetAddresses("6105");
        XmlDocument xmlDoc = new XmlDocument();
        xmlDoc.LoadXml(strData);
        XmlNodeReader nRead = new XmlNodeReader(xmlDoc);
        DataSet d = new DataSet();
        d.ReadXml(nRead);
        nRead.Close();
        GridView1.DataSource = d;
        GridView1.DataBind();
    }
    
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IAddressService")]
public interface IAddressService
{

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IAddressService/GetAddresses", ReplyAction = "http://tempuri.org/IAddressService/GetAddressesResponse")]
    string GetAddresses(string strZIP);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IAddressServiceChannel : IAddressService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class AddressServiceClient : System.ServiceModel.ClientBase<IAddressService>, IAddressService
{

    public AddressServiceClient()
    {
    }

    public AddressServiceClient(string endpointConfigurationName)
        :
            base(endpointConfigurationName)
    {
    }

    public AddressServiceClient(string endpointConfigurationName, string remoteAddress)
        :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public AddressServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress)
        :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public AddressServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress)
        :
            base(binding, remoteAddress)
    {
    }

    public string GetAddresses(string strZIP)
    {
        return base.Channel.GetAddresses(strZIP);
    }
}
